name: Gerar EXE

on:
  push:
    branches:
      - Labirinto

jobs:

  build:

    runs-on: windows-latest

    steps:

      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Gerar executavel
        run: |
          pyinstaller --onefile --noconsole labirinto_bfs_dfs.py

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: Labirinto-BFS-DFS
          path: dist/*